'use strict'

const labels = {
    es: {
        'its.not.resica.file': 'El elemento seleccionado no es un directorio o archivo Resica',
        'conf.saved.successfully': 'La configuración se guardó exitosamente',
        'conf.not.saved': 'La configuración no fue guardada',
        'pdf.catalog.generated.successfully': 'El catálogo PDF fue generado exitosamente',
        'pdf.catalog.not.generated': 'El catálogo PDF no fue generado',
        'operation.not.completed': 'Operación no completada',
        'size.and.price.are.required': 'Debe ingresar el tamaño y el precio',
        'operation.completed': 'Operación completada',
        'product.saved.successfully': 'El item se guardó exitosamente',
        'product.not.saved': 'El item no se guardó',
        'confirmation': 'Confirmación',
        'create.new.directory': 'Está seguro de que desea crear un nuevo directorio de compañía en',
        'error': 'Error',
        'new.directory.must.empty': 'El nuevo directorio de compañía debe estar vacío',
        'new.company.created.successfully': 'La nueva compañía fue creada exitosamente',
        'new.company.not.created': 'La nueva compañía no fue creada',
        'add': 'Agregar',
        'remove': 'Remover',
        'print': 'Imprimir',
        'save': 'Guardar',
        'select.a.product': 'Seleccione un producto:',
        'create.example.company': 'Crear compañia de ejemplo',
        'general.conf': 'Configuración General',
        'general.conf.title': 'Título',
        'general.conf.company': 'Compañía',
        'general.conf.whatsapp': 'Whatsapp',
        'general.conf.instagram': 'Instagram',
        'general.conf.print.options': 'Opciones de Impresión',
        'general.conf.print.options.show.code': 'Mostrar código',
        'general.conf.print.options.show.name': 'Mostrar nombre',
        'general.conf.print.options.show.description': 'Mostrar descripción',
        'general.conf.print.options.show.prices': 'Mostrar precios',
        'general.conf.print.options.show.observations': 'Mostrar observaciones',
        'item.data': 'Datos de Ítem',
        'item.data.code': 'Código',
        'item.data.name': 'Nombre',
        'item.data.description': 'Descripción',
        'item.data.prices': 'Precios',
        'item.data.prices.size': 'Tamaño',
        'item.data.prices.price': 'Precio',
        'item.data.prices.table.size': 'Tamaño',
        'item.data.prices.table.price': 'Precio',
        'item.data.prices.table.delete': 'Eliminar',
        'item.data.observations': 'Observaciones',
        'item.data.active': 'Activo',
    },
    en: {
        'its.not.resica.file': `The selected element it's not a Resica directory or Resica file`,
        'conf.saved.successfully': 'The configuration was saved successfully',
        'conf.not.saved': 'The configuration was not saved',
        'pdf.catalog.generated.successfully': 'The PDF catalog was saved saved successfully',
        'pdf.catalog.not.generated': 'The PFD catalog was not generated',
        'operation.not.completed': 'Operation not completed',
        'size.and.price.are.required': 'Size and Price are required',
        'operation.completed': 'Operation completed',
        'product.saved.successfully': 'The item was saved successfully',
        'product.not.saved': 'The item was not saved',
        'confirmation': 'Confirmación',
        'create.new.directory': 'Are you sure you want to create a new company directory in ',
        'error': 'Error',
        'new.directory.must.empty': 'The new company directory must be empty',
        'new.company.created.successfully': 'The new company was created successfully',
        'new.company.not.created': 'The new company was not created',
        'add': 'Add',
        'remove': 'Remove',
        'print': 'Print',
        'save': 'Save',
        'select.a.product': 'Select a product',
        'create.example.company': 'Create example company',
        'general.conf': 'General Configuration',
        'general.conf.title': 'Title',
        'general.conf.company': 'Company',
        'general.conf.whatsapp': 'Whatsapp',
        'general.conf.instagram': 'Instagram',
        'general.conf.print.options': 'Print Options',
        'general.conf.print.options.show.code': 'Show code',
        'general.conf.print.options.show.name': 'Show name',
        'general.conf.print.options.show.description': 'Show description',
        'general.conf.print.options.show.prices': 'Show prices',
        'general.conf.print.options.show.observations': 'Show observations',
        'item.data': 'Item Data',
        'item.data.code': 'Code',
        'item.data.name': 'Name',
        'item.data.description': 'Description',
        'item.data.prices': 'Prices',
        'item.data.prices.size': 'Size',
        'item.data.prices.price': 'Price',
        'item.data.prices.table.size': 'Size',
        'item.data.prices.table.price': 'Price',
        'item.data.prices.table.delete': 'Delete',
        'item.data.observations': 'Observations',
        'item.data.active': 'Active',
    }
}

function getLabels(lang) {
    return labels[lang]
}

module.exports = {
    getLabels
}
